//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDemoC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice_details
    {
        public int detail_id { get; set; }
        public Nullable<int> invoice_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public int quantity { get; set; }
        public decimal price { get; set; }
        public decimal subtotal { get; set; }
        public bool active { get; set; }
    
        public virtual invoices invoices { get; set; }
        public virtual products products { get; set; }
    }
}
